from django.urls import path, include

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('register/', views.register, name='register'),
    path("user/", views.userpage, name="userpage"),
    path('woj/add/', views.crwoj.as_view(), name="addwoj"),
    path('woj/<int:pk>', views.upwoj.as_view(), name="upwoj"),
    path('woj/<int:pk>/del/', views.dewoj.as_view(), name="rmwoj"),
    path('woj/', views.woj, name="woj"),
    path('acode/add/', views.cracode.as_view()),
    path('acode/<int:pk>', views.upacode.as_view()),
    path('acode/<int:pk>/del/', views.deacode.as_view()),
    path('acode/', views.woj, name="acode"),
    path('adres/add/', views.cradres.as_view()),
    path('adres/<int:pk>', views.upadres.as_view(), name='adres_up'),
    path('adres/<int:pk>/del/', views.deadres.as_view(), name='adres_del'),
    path('adres/', views.woj, name="adres"),
    path('adres/test/<int:pk>', views.seeadres.as_view(), name='adres_det'),
    path('stadion/add/', views.crstadion.as_view()),
    path('stadion/<int:pk>', views.upstadion.as_view()),
    path('stadion/<int:pk>/del/', views.destadion.as_view()),
    path('stadion/', views.stadion, name="stadion"),
    path('zawody/', views.zawody, name="zawody"),
    path('zawody/add/', views.crzawody.as_view()),
    path('zawody/<int:pk>', views.upzawody.as_view()),
    path('zawody/<int:pk>/del/', views.dezawody.as_view()),
    path('zawody/<strona>', views.article, name="article"),
    path('team/', views.team, name="team"),
    path('team/add/', views.crteam.as_view()),
    path('team/<int:pk>', views.upteam.as_view()),
    path('team/<int:pk>/del/', views.deteam.as_view()),
    path('osoba/', views.osoba, name="osoba"),
    path('osoba/add/', views.crosoba.as_view()),
    path('osoba/<int:pk>', views.uposoba.as_view()),
    path('osoba/<int:pk>/del/', views.deosoba.as_view()),
    path('dyscyplina/', views.dyscyplina, name='dyscyplina'),
    path('dyscyplina/add/', views.crdyscyplina.as_view()),
    path('dyscyplina/<int:pk>', views.updyscyplina.as_view()),
    path('dyscyplina/<int:pk>/del/', views.dedyscyplina.as_view()),
    path('lista_zawodnikow/', views.lista_zawodnikow, name='lz'),
    path('lista_zawodnikow/add/', views.crlista_zawodnikow.as_view()),
    path('lista_zawodnikow/<int:pk>', views.uplista_zawodnikow.as_view()),
    path('lista_zawodnikow/<int:pk>/del/', views.delista_zawodnikow.as_view()),
    path('szatnia/', views.szatnie, name='szatnia'),
    path('szatnia/add/', views.crszatnie.as_view()),
    path('szatnia/<int:pk>', views.upszatnie.as_view()),
    path('szatnia/<int:pk>/del/', views.deszatnie.as_view()),
    path('test/', views.test),
]
