# Generated by Django 3.2.3 on 2021-05-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZIP', models.CharField(max_length=5)),
                ('Miasto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ulica', models.CharField(max_length=40)),
                ('NrDomu', models.IntegerField(default=0)),
                ('NrLokalu', models.IntegerField(default=0)),
                ('Acode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.acode')),
            ],
        ),
        migrations.CreateModel(
            name='Dyscyplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyscyplina_nazwa', models.CharField(max_length=100)),
                ('top_1', models.IntegerField(blank=True, default=0, null=True)),
                ('top_2', models.IntegerField(blank=True, default=0, null=True)),
                ('top_3', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadion_nazwa', models.CharField(max_length=100, unique=True)),
                ('pojemnosc_trybun', models.IntegerField(blank=True, default=0, null=True)),
                ('niepelnosprawni', models.BooleanField(default=False)),
                ('stadion_adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.adres')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_nazwa', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woj_nazwa', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zawody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zawody_nazwa', models.CharField(max_length=200)),
                ('zawody_data', models.DateTimeField(blank=True, null=True)),
                ('stadion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.stadion')),
            ],
        ),
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zawodnik_imie', models.CharField(max_length=50)),
                ('zawodnik_nazwisko', models.CharField(max_length=50)),
                ('zawodnik_wiek', models.IntegerField(default=0)),
                ('zawodnik_telefon', models.IntegerField(default=0)),
                ('zawodnik_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('trener_team', models.ManyToManyField(to='polls.Team')),
                ('zawodnik_adres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.adres')),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trener_imie', models.CharField(max_length=50)),
                ('trener_nazwisko', models.CharField(max_length=50)),
                ('trener_wiek', models.IntegerField(default=0)),
                ('trener_telefon', models.IntegerField(default=0)),
                ('trener_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('trener_adres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.adres')),
                ('trener_team', models.ManyToManyField(to='polls.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Szatnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.team')),
                ('zawody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.zawody')),
            ],
        ),
        migrations.AddField(
            model_name='acode',
            name='Woj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.wojewodztwo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.trener'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zawodnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.zawodnik'),
        ),
    ]
