# Generated by Django 3.2.3 on 2021-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210525_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='trener',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zawodnik',
        ),
        migrations.AddField(
            model_name='profile',
            name='zawody',
            field=models.ManyToManyField(to='polls.Zawody'),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
