# Generated by Django 3.2.3 on 2021-05-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210525_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyscyplina',
            name='zaw_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dyscyplina',
            name='zaw_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dyscyplina',
            name='zaw_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dyscyplina',
            name='top_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dyscyplina',
            name='top_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dyscyplina',
            name='top_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Lista_Zawodnikow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Czas_Odleglosc', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('Dyscyplina', models.ManyToManyField(to='polls.Dyscyplina')),
                ('Zawodnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.zawodnik')),
                ('Zawody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.zawody')),
            ],
        ),
    ]
