# Generated by Django 3.2.3 on 2021-05-25 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210525_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='zawody',
            name='aff_url',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zawody',
            name='zawody_pub',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
