# Generated by Django 3.2.3 on 2021-05-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_acode_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='Acode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.acode'),
        ),
    ]
