# Generated by Django 3.2.3 on 2021-05-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_adres_acode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='Acode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.acode'),
        ),
    ]
