# Generated by Django 3.2.3 on 2021-05-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_adres_acode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadion',
            name='naw_av',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='stadion',
            name='org_av',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='stadion',
            name='stadion_zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='polls/images/'),
        ),
        migrations.AddField(
            model_name='stadion',
            name='sza_av',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nawierzchnia', models.IntegerField(default=0)),
                ('szatnie', models.IntegerField(default=0)),
                ('organizacja', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.profile')),
                ('stadion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.stadion')),
            ],
        ),
    ]
