# Generated by Django 3.2.3 on 2021-05-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_stadion_stadion_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='acode',
            name='Adres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.adres'),
        ),
    ]
