# Generated by Django 3.2.3 on 2021-05-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_acode_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='Acode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_titles', to='polls.acode'),
        ),
    ]
