# Generated by Django 3.2.3 on 2021-05-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_adres_acode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trener',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.trener'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zawodnik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.zawodnik'),
        ),
    ]
