# Generated by Django 3.2.3 on 2021-05-29 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20210529_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zawody',
            name='zawody_nazwa',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='zawody',
            name='zawody_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
