# Generated by Django 3.2.3 on 2021-05-29 18:47

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_zawody_zawody_data'),
    ]

    operations = [

    ]
