# Generated by Django 3.2.3 on 2021-05-29 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_zawody_zawody_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zawody',
            name='zawody_data',
            field=models.DateField(default=datetime.datetime(2021, 6, 5, 18, 49, 47, 420771, tzinfo=utc), verbose_name='Kiedy'),
        ),
    ]
