# Generated by Django 3.2.3 on 2021-05-29 18:55

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_zawody_zawody_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zawody',
            name='zawody_data',
            field=models.DateTimeField(default=polls.models.return_date_time, verbose_name='Kiedy'),
        ),
    ]
