# Generated by Django 3.2.3 on 2021-05-29 19:58

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20210529_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zawody',
            name='zawody_data',
            field=models.DateTimeField(default=polls.models.return_date_time, help_text='<em>DD.MM.YYYY HH:MM</em>', verbose_name='Kiedy'),
        ),
    ]
