# Generated by Django 3.2.3 on 2021-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_zawody_zawody_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_nazwa',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa_drużyny'),
        ),
    ]
