# Generated by Django 3.2.3 on 2021-05-30 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_team_team_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadion',
            name='niepelnosprawni',
            field=models.BooleanField(default=False, verbose_name='Niepełnosprawni'),
        ),
        migrations.AlterField(
            model_name='stadion',
            name='pojemnosc_trybun',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pojemność trybun'),
        ),
        migrations.AlterField(
            model_name='stadion',
            name='stadion_adres',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.adres', verbose_name='Adres stadionu'),
        ),
        migrations.AlterField(
            model_name='stadion',
            name='stadion_nazwa',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa stadionu'),
        ),
        migrations.AlterField(
            model_name='stadion',
            name='stadion_zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='polls/images/', verbose_name='Zdjęcie stadionu'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_nazwa',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa drużyny'),
        ),
    ]
