# Generated by Django 3.2.3 on 2021-05-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20210530_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='trener',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zawodnik',
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('wiek', models.IntegerField(default=0)),
                ('telefon', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('zawodnik', 'Konto zawodnika'), ('trener', 'Konto trenera')], default='zawodnik', max_length=20)),
                ('adres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.adres')),
                ('team', models.ManyToManyField(to='polls.Team')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='osoba',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.osoba'),
        ),
    ]
