# Generated by Django 3.2.3 on 2021-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20210530_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='polls/images/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='telefon',
            field=models.IntegerField(default=0, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='wiek',
            field=models.IntegerField(default=0, verbose_name='Wiek'),
        ),
    ]
