# Generated by Django 3.2.3 on 2021-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_osoba_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='polls/images/', verbose_name='Zdjęcie'),
        ),
    ]
