# Generated by Django 3.2.3 on 2021-05-30 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20210530_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='wiek',
        ),
        migrations.AddField(
            model_name='osoba',
            name='data_urodzenia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Urodzenia'),
        ),
    ]
