# Generated by Django 3.2.3 on 2021-05-30 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_alter_adres_nrlokalu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='telefon',
            field=models.IntegerField(max_length=1, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi być w formacie: '+999999999'. Dozwolone 15. cyfr.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon'),
        ),
    ]
