# Generated by Django 3.2.3 on 2021-05-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_alter_osoba_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='telefon',
        ),
    ]
