# Generated by Django 3.2.3 on 2021-05-30 17:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_remove_osoba_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='email',
            field=models.EmailField(blank=True, default='999999999', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
