# Generated by Django 3.2.3 on 2021-05-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_alter_osoba_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zawody',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Zawody'),
        ),
    ]
