# Generated by Django 3.2.3 on 2021-05-31 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_alter_profile_zawody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zawody',
            field=models.ManyToManyField(blank=True, to='polls.Zawody'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.profile'),
        ),
    ]
