# Generated by Django 3.2.3 on 2021-05-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_auto_20210531_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.profile', unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='stadion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.stadion', unique=True),
        ),
    ]
