# Generated by Django 3.2.3 on 2021-05-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_auto_20210531_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='stadion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.stadion'),
        ),
    ]
