# Generated by Django 3.2.3 on 2021-05-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_alter_vote_profile'),
    ]

    operations = [

    ]
