# Generated by Django 3.2.3 on 2021-05-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='szatnia',
            name='pokoj',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.RemoveField(
            model_name='lista_zawodnikow',
            name='Dyscyplina',
        ),
        migrations.AddField(
            model_name='lista_zawodnikow',
            name='Dyscyplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.dyscyplina'),
        ),
    ]
