# Generated by Django 3.2.3 on 2021-05-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_auto_20210531_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_zawodnikow',
            name='Zawodnik',
        ),
        migrations.AddField(
            model_name='lista_zawodnikow',
            name='Osoba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.osoba'),
        ),
    ]
