# Generated by Django 3.2.3 on 2021-05-31 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_auto_20210531_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyscyplina',
            name='zaw_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uno', to='polls.osoba'),
        ),
        migrations.AlterField(
            model_name='dyscyplina',
            name='zaw_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dos', to='polls.osoba'),
        ),
        migrations.AlterField(
            model_name='dyscyplina',
            name='zaw_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tres', to='polls.osoba'),
        ),
    ]
