# Generated by Django 3.2.3 on 2021-05-31 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_auto_20210531_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_zawodnikow',
            name='Zawody',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.zawody'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='data_urodzenia',
            field=models.DateField(default=django.utils.timezone.now, help_text='dd.mm.rrrr', verbose_name='Data Urodzenia'),
        ),
    ]
